version: '3.8'

services:
  web:
    build: .
    ports:
      - "5003:5003"
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - DATABASE_URL=sqlite:///fraud_detection.db
      - MLFLOW_TRACKING_URI=http://mlflow:5004
    volumes:
      - .:/app

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.0.1
    platform: linux/amd64
    ports:
      - "5004:5004"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5004
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0 --port 5004
    volumes:
      - ./mlruns:/mlflow/artifacts
    restart: always




