artifact_location: /Users/lisaschweinester/PycharmProjects/From_Model_To_Production2/azure_blob:/fraud.blob.core.windows.net/fraud_1726588205992?RI0ldUrrmVb8RLqezjS2ZMjQChQC6LMaeQszfXmt/e/rmQxdBtasnC6ChK5QcdPUkY4MFfSLEv3T+AStR3iZZA==/675573846331234381
creation_time: 1726589209594
experiment_id: '675573846331234381'
last_update_time: 1726589209594
lifecycle_stage: active
name: experiment
