name: Data Drift Check

on:
  workflow_dispatch:
    inputs:
      timestamp:
        description: 'Timestamp for the workflow'
        required: true
        default: '2024-08-11T00:00:00Z'
      db_connection_url:
        description: 'Database connection URL'
        required: true
        default: 'mssql+pyodbc://adminuser:FraudDetection1!@fraud-detection-server.database.windows.net:1433/fraud_detection_db?driver=ODBC+Driver+17+for+SQL+Server'

jobs:
  check-data-drift:
    runs-on: ubuntu-latest

    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      MLFLOW_TRACKING_URI: http://localhost:5004

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get install -y unixodbc-dev
        pip install -r requirements.txt

    - name: Run data drift check
      run: |
        python app/models/data_drift_check.py "${{ github.event.inputs.timestamp }}" "${{ github.event.inputs.db_connection_url }}"

    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: ${{ github.workspace }}/mlruns/
