name: Build, Test, and Monthly Retraining

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'  # Monthly retraining schedule
  workflow_dispatch:  # Manually trigger for build and test

jobs:
  build-and-test:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: my-image:latest

      - name: Run tests
        run: |
          docker run --rm my-image:latest pytest

  monthly-retraining:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Monthly Retraining
        run: |
          python app/retrain.py

  simulation-test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up environment variables
        run: echo "MLFLOW_TRACKING_URI=http://mlflow:5004" >> $GITHUB_ENV

      - name: Generate data for the year
        run: |
          PYTHONPATH=app python -m generate_fake_data

      - name: Simulate data and retraining for each week
        run: |
          PYTHONPATH=app python -m data_insertion

