name: Monthly Retraining

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'  # Run on the first day of every month at midnight UTC

jobs:
  retrain:
    runs-on: ubuntu-latest

    services:
      mlflow:
        image: ghcr.io/mlflow/mlflow:v2.0.1
        ports:
          - 5004:5004
        options: >-
          --mount type=bind,source=${{ github.workspace }}/mlruns,target=/mlflow/artifacts
        env:
          MLFLOW_TRACKING_URI: http://localhost:5004

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create mlruns directory
        run: mkdir -p ${{ github.workspace }}/mlruns

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up environment variables
        run: echo "MLFLOW_TRACKING_URI=http://localhost:5004" >> $GITHUB_ENV

      - name: Run Monthly Retraining
        run: |
          python app/retrain.py
