name: Monthly Retraining

on:
  schedule:
    - cron: '*/1 * * * *'
    #- cron: '0 0 1 * *'  # Run at midnight UTC on the first day of every month

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up MLflow environment variables
        run: echo "MLFLOW_TRACKING_URI=http://localhost:5004" >> $GITHUB_ENV

      - name: Start MLflow server
        run: |
          mkdir -p mlruns
          mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 --port 5004 &

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run Monthly Retraining
        run: |
          python app/models/retrain.py

