name: MLOps Simulation Test

on:
  workflow_dispatch:  # Manually trigger this workflow

jobs:
  simulate-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true  # Fetch Git LFS files

    - name: Set up Git LFS
      run: |
          git lfs install
          git lfs pull

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    #- name: List files in app directory
     # run: |
      #    ls -la app/
       #   cat app/Fraud.csv  # Print contents of the CSV file

    - name: Generate data for the year
      run: |
        python app/generate_fake_data.py

    - name: Simulate data and retraining for each week
      run: |
        python app/data_insertion.py

