name: Simulation Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install Flask-Testing
          pip install mlflow

      - name: Set up environment variables
        run: echo "MLFLOW_TRACKING_URI=http://localhost:5004" >> $GITHUB_ENV

      - name: Create mlruns directory
        run: mkdir -p ${{ github.workspace }}/mlruns

      - name: Run MLflow
        run: |
          nohup mlflow server --backend-store-uri sqlite:///${{ github.workspace }}/mlruns --default-artifact-root=${{ github.workspace }}/mlruns/artifacts --host 0.0.0.0 --port 5004 &

      - name: Generate simulated data
        run: |
          python app/generate_fake_data.py
          mkdir -p simulated_data
          mv simulated_data_year.csv simulated_data/

      - name: Upload Simulated Data
        uses: actions/upload-artifact@v3
        with:
          name: simulated-data
          path: simulated_data/simulated_data_year.csv

      - name: Download Simulated Data
        uses: actions/download-artifact@v3
        with:
          name: simulated-data

      - name: Create directory
        run: mkdir -p app/simulated_data

      - name: Move Simulated Data
        run: mv simulated-data/simulated_data_year.csv app/simulated_data/

      - name: Run Simulation Tests
        run: python -m unittest discover -s tests -p "test_simulation.py"
